### ISSUE TITLE
Moodle Docs for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [junpataleta/moodle-mod_threesixo#10]
Hi,
Congratulations on this 360-degrees feedback plugin. I like it a lot.

I hope you don't mind that I created a Moodle documentation page at https://docs.moodle.org/all/es/360-degree_feedback_module .

This page is shown when a user clicks on the 'Moodle Docs for this page' while setting up a 360 instance.

I am currently making a Spanish translation for that page.

Please feel free to add/remove/change as you see fit.

**Comment by junpataleta** [comment]
That's great! Thanks! (Apologies for the late reply!)
