### ISSUE TITLE
Student can change their feedback after ending date

### ISSUE THREAD

**Issue by Fransipani** [junpataleta/moodle-mod_threesixo#13]
A a teacher you can provide a start and end date in which student can give feedback.
I discovered that student still can change their feedback (that they already gave) after the closing time.

**Comment by junpataleta** [comment]
Thanks for reporting this issue.
This has been fixed for the [v37.0.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/37.0.0), [v36.1.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/36.1.0), and [v35.4.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/35.4.0) releases of this plugin which will be made available in the Moodle plugins site shortly.
