### ISSUE TITLE
Update release feedback to students

### ISSUE THREAD

**Issue by Fransipani** [junpataleta/moodle-mod_threesixo#14]
I want to use this 360 degrees activity as a peerfeedback activity. Therefore it is important that students can see the feedback that was given to them

**Comment by junpataleta** [comment]
Apologies for the late response. This feature has now been implemented in versions [3.5.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/35.3.0) and up of the plugin!

I'll proceed to close this now.

Thanks!
