### ISSUE TITLE
Cannot use groups or groupings

### ISSUE THREAD

**Issue by upats** [junpataleta/moodle-mod_threesixo#16]
Hello, awesome plugin! To use this I would need the capability to assign groups/groupings under Common Module settings, or maybe even better under General settings next to the Participants choice. Instructors want to use this for peer feedback on group projects, and limit students to evaluating A) their group teammates and B) self-evaluating. I saw on the plugin page that groups are maybe supported. But I have installed the 36 branch and there is no option for groups in the plugin settings. Many thanks!

**Comment by junpataleta** [comment]
Thanks for reporting this issue.
Groups and grouping functionality has been fixed for the [v37.0.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/37.0.0), [v36.1.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/36.1.0), and [v35.4.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/35.4.0) releases of this plugin which will be made available in the Moodle plugins site shortly.
