### ISSUE TITLE
Clicking 360 feedbacks in activities block takes you to a blank page

### ISSUE THREAD

**Issue by tonyyeb** [junpataleta/moodle-mod_threesixo#17]
Hi 

Clicking the 360 feedbacks link in a course activities blocks takes a user to: /mod/threesixo/index.php?id=2 which is blank.

Thanks

Chris

**Comment by junpataleta** [comment]
Thanks for the report! This has been fixed in 15acc70f192c40fe132f81ca69073c06eb387326.

Closing this issue.
