### ISSUE TITLE
no buttons Yes/No

### ISSUE THREAD

**Issue by Scrik** [junpataleta/moodle-mod_threesixo#20]
![Снимок экрана от 2020-01-13 11-12-46](https://user-images.githubusercontent.com/5807097/72250988-f4ef0000-360d-11ea-8d1d-f3ef8a7896b2.png)

Version Moodle 3.8
Version treesix 37.0

**Comment by Scrik** [comment]
help @junpataleta

**Comment by junpataleta** [comment]
Thanks for reporting this. Apologies for the late response. This issue has now been fixed in the latest version of the plugin.
