### ISSUE TITLE
Unable to delete 360 degree course.

### ISSUE THREAD

**Issue by cspguy** [junpataleta/moodle-mod_threesixo#22]
It is not possible to delete the entire 360 degree course, after creation.
There is no "bucket" icon near the name of the course.

**Comment by junpataleta** [comment]
Hi, thanks for reporting this issue. Apologies for the delay in response. Just to clarify, so if a course has a 360-degree feedback activity in it, then the course cannot be deleted in the "Manage courses and categories" page? If so, perhaps could this be a capability issue in your site? I tried reproducing this issue but I couldn't. I can delete a course fine even if it has 360-degree feedback in it.
I'll be closing this issue.
Cheers!
