### ISSUE TITLE
Bug in version v38.0.0 (2019111800) to Moodle 3.10

### ISSUE THREAD

**Issue by angela-araujo** [junpataleta/moodle-mod_threesixo#26]
There is one problem to show the questions and rations in Moodle 3.10.
To solve, I think:
- In file questionnaire.mustache: Replace class **.row-fluid** to **.row**
- In file questionnaire.mustache: Replace all classes **.label** to **.badge**, because label is deprecated in Bootstrap v5.0 (https://getbootstrap.com/docs/5.0/components/badge/)
- Change the all files js to adapte all classes labels (label-success, label-default) to classes badges (badge-success, bg-secondary)

![mod_threesixo_bug_moodle310](https://user-images.githubusercontent.com/6721903/115482798-dbcbfa80-a225-11eb-9001-76341a58c5ec.png)

**Comment by junpataleta** [comment]
Thanks, Angela! 

This has been fixed in 9342c5a and will be included in the next release.

Closing this issue.

Cheers!
