### ISSUE TITLE
Showing Suspended Students

### ISSUE THREAD

**Issue by levyian** [junpataleta/moodle-mod_threesixo#28]
Congrats on the plugin.

We're expanding the use of this tool at our university and we ran into a strange issue. Students who are suspended from the course, or whose enrollment has expired, still show up in the feedback. This seems like a major bug, is there a setting that we need to use to fix it? If not, is this something you would be able to address soon?

**Comment by junpataleta** [comment]
HI! Thanks for the report. I'll have a look and provide a fix soon.

Cheers!

**Comment by levyian** [comment]
Awesome. Thanks!

**Comment by junpataleta** [comment]
Apologies for the delay. This has been fixed in https://github.com/junpataleta/moodle-mod_threesixo/commit/23a27fa41ea10627238ca61d6b44443404beca51 and will be included in the plugin's next release.

**Comment by levyian** [comment]
Hi @junpataleta, Thanks for updating the plugin. I ran into an issue when I tried to update it. It looks like it's only available for Moodle 3.10 and 3.11. I think I read somewhere that you only focus on the last two Moodle versions due to constraints. Is that correct?

I'm wondering if you can make an exception for v3.9 since it's the LTS version. It has security updates that extend beyond the latest two, which could be helpful to many.

Thanks!
