### ISSUE TITLE
Error when logged as user

### ISSUE THREAD

**Issue by martinvivek** [junpataleta/moodle-mod_threesixo#3]
As an admin, i clicked some feedback for the user. and save changes and submit.
Now logged as a user and found the below error
![image](https://user-images.githubusercontent.com/7712010/35283128-5864cb6a-007d-11e8-8eee-72ac8ceda77d.png)

**Comment by junpataleta** [comment]
Thanks for reporting this, Vivek. Fix provided: https://github.com/junpataleta/moodle-mod_threesixo/commit/6323f916950c5406ff023b9b86eaacb27900ca1c.
