### ISSUE TITLE
Suppport Moodle LTS Versions

### ISSUE THREAD

**Issue by levyian** [junpataleta/moodle-mod_threesixo#31]
Hi @junpataleta, Thanks for updating the plugin in issue #28. I ran into a problem when I tried to update it as it looks like it's only available for Moodle 3.10 and 3.11. I think I read somewhere that you only focus on the last two Moodle versions due to constraints. Is that correct?

I'm wondering if you can make an exception for v3.9 since it's the LTS version. It has security updates that extend beyond the latest two, which could be helpful to many.

Thanks!

**Comment by junpataleta** [comment]
Thanks. I have released  v3.9.0 of the plugin which basically includes the bug fixes in v3.10.1 and is aimed for Moodle 3.9.

Hope this helps.
