### ISSUE TITLE
Unreal average results

### ISSUE THREAD

**Issue by komarovi4** [junpataleta/moodle-mod_threesixo#34]
So, I have some mystic results with unreal average result. (It was in anonymous feedback). 

![incredible_results](https://github.com/junpataleta/moodle-mod_threesixo/assets/93541069/8e60f847-bbec-4b42-9bdd-3bf6fc20ce97)

<img width="640" alt="incredible_results_2" src="https://github.com/junpataleta/moodle-mod_threesixo/assets/93541069/278b0521-6843-44bc-b4bc-3bd4ef773bcd">

**Comment by junpataleta** [comment]
Wow... Thanks for the report. I'll look into this and put up a fix soon.

**Comment by junpataleta** [comment]
Thanks for your patience! 

This issue is now fixed in the latest version of the plugin ([v4.0.1](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/v4.0.1)). I'll be publishing the new version on the plugins directory soon.
