### ISSUE TITLE
Decline Review

### ISSUE THREAD

**Issue by dbnschools** [junpataleta/moodle-mod_threesixo#5]
If I click to decline a review can I also change my mind?  How do I re-enable the ability to review someone?  I can see an issue where someone accidently clicks that button and then changes their mind.  Can a teacher or site admin reverse that decision?

**Comment by junpataleta** [comment]
Thanks for the suggestion! I think this is a great idea and I'll try to work on it. Cheers!

**Comment by markn86** [comment]
Any update on this?

**Comment by junpataleta** [comment]
Closing this, issue. This has been implemented in f4350c9d54b6e81f65cb9b5af2898afc0f18bdbc and will be part of v36.0.0 and v35.3.0
