### ISSUE TITLE
Feedback for self

### ISSUE THREAD

**Issue by harshitnayak45** [junpataleta/moodle-mod_threesixo#7]
Hi,

I wanted the user to give feedback for self. I have found a function in api.php file get_participants() and that function have parameter $includeself = false so i have set that to true. User is hown but there is no button for give feedback. Please check screenshothttps://drive.google.com/file/d/1oQr73xhsnUDSTuBAuXzqCBiBuFV0lKlV/view?usp=drivesdk Can you please help me on that ASAP.

Thanks

**Comment by junpataleta** [comment]
Apologies for the late response.

Self-review is now available for versions [35.1.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/35.1.0) and [34.2.0](https://github.com/junpataleta/moodle-mod_threesixo/releases/tag/34.2.0) of the plugin.

Closing this.
