### ISSUE TITLE
Unable to open 'Api documentation'

### ISSUE THREAD

**Issue by Richardvi** [junpataleta/moodle-mod_threesixo#8]
When trying to open 'Api Documentation' 

/admin/webservice/documentation.php

I'm getting this error:

Coding error detected, it must be fixed by a programmer: **Missing implementation method of mod_threesixo\external::submit_feedback**
More information about this error
×Debug info: 
Error code: codingerror
×Stack trace:
•	line 102 of /lib/externallib.php: coding_exception thrown
•	line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()

It seems something is not implemented correctly concerning the webservices?

**Comment by Richardvi** [comment]
Is this supported? I will remove this plugin for the time being as the problem described above will give us problems.

**Comment by junpataleta** [comment]
Hi Richard,

Apologies for not being able to get back to you soon. 

This issue has been fixed in 043b4f6e1136a9531217ced4ad405428806c0cac for the 3.5 version and bc91b4b364d1899ec94aab98cf061eee1c1df113 for the 3.4 version.

This fix is now available on the latest release of the plugin.

Thanks!

**Comment by Richardvi** [comment]
Hi Jun!

Apologies are of course not necessary. Your update has been installed and everything works great again!

Have a nice summer,

Richard.
